### ISSUE TITLE
Configure CF Push for subfolder

### ISSUE THREAD

**Issue by rangulvers** [jhunt/cf-push#1]
Hi jhunt, 

maybe I missed it in reading the GH Action docs but I want to use your cf-push workflow to only push a specify sub-folder in a repo. Is this possible? 

The workflow would be to list to changes to a specific folder and then push the cf app in this folder. This way I can have multiple CF apps in in repo for learning reasons

Thanks

**Comment by jhunt** [comment]
You would need to modify the entrypoint.sh to chdir before doing cf-y things.
